version: '3.8'

services:
  talk_rater_db:
    container_name: "talk_rater_postgresql"
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - "9000:5432"
    environment:
      POSTGRES_USER: telegram_bot
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

      POSTGRES_DB: talk_rater_db
    networks:
      - backend
    volumes:
      - talk_rater_data:/var/lib/postgresql/data
    secrets:
      - db_password
  talk_rater_bot:
    depends_on:
      - talk_rater_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      TG_API_TOKEN_USER_FILE: /run/secrets/tg_api_token_user
      TG_API_TOKEN_ADMIN_FILE: /run/secrets/tg_api_token_admin
    # restart: unless-stopped
    networks:
      - backend
    secrets:
      - db_password
      - tg_api_token_admin
      - tg_api_token_user

secrets:
  db_password:
    file: ./secrets/db_password.txt
  tg_api_token_admin:
    file: ./secrets/tg_api_token_admin.txt
  tg_api_token_user:
    file: ./secrets/tg_api_token_user.txt

networks:
  backend:
    driver: bridge

volumes:
  talk_rater_data:
