version: '3.8'

services:
  talk_rater_db:
    container_name: "postgresql-alpine"
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - "9000:5432"
    environment:
      POSTGRES_USER: telegram_bot
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password.txt

      POSTGRES_DB: talk_rater_db
    networks:
      - backend
    volumes:
      - talk_rater_data:/var/lib/postgresql/data
      - ./secrets/db_password.txt:/run/secrets/db_password.txt

  talk_rater_bot:
    depends_on:
      - talk_rater_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password.txt
      TG_API_TOKEN_USER_FILE: /run/secrets/tg_api_token_user.txt
      TG_API_TOKEN_ADMIN_FILE: /run/secrets/tg_api_token_admin.txt
      CONFIG_PATH_TG_BOT: /run/configs/local.yaml

      PATH_LOGS: /tmp/logs.json
      TEMPLATE_PATH: /templates
    # restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./tmp_files:/tmp
      - ./templates:/templates
      - ./secrets:/run/secrets
      - ./config:/run/configs

networks:
  backend:
    driver: bridge

volumes:
  talk_rater_data:
    driver: local