package data

import (
	"time"
)

type User struct {
	ID                int64 // info from Telegram
	UserName          string
	IdentityInfo      string
	CreatedAt         time.Time  // auto generated by gorm
	FavouriteLectures []*Lecture `gorm:"many2many:user_lectures;"`
}
